name: olaf

motor_manager_config_file: ../config/hardware/motor/olaf.yaml
sensor_manager_config_file: ../config/hardware/sensor/xsens_mti.yaml
urdf_file: ../config/robot/olaf/olaf.urdf

motors:
  - name: left_hip_yaw
    index: 0
  - name: left_hip_roll
    index: 6
  - name: left_hip_pitch
    index: 4
  - name: left_knee
    index: 5
  - name: left_ankle_pitch
    index: 2
  - name: left_ankle_roll
    index: 3
  - name: right_hip_yaw
    index: 1
  - name: right_hip_roll
    index: 7
  - name: right_hip_pitch
    index: 8
  - name: right_knee
    index: 9
  - name: right_ankle_pitch
    index: 10
  - name: right_ankle_roll
    index: 11

sensors:
  - name: imu_body
    index: 0
    frame: pelvis
    translation: [-0.04688, 0.0, 0.31825]
    orientation: [0.0, 0.0, 0.0, 1.0]

foots:
  - name: left_foot_link
    offset: [0.026, 0.0, -0.051]
  - name: right_foot_link
    offset: [0.026, 0.0, -0.051]