masters:
  - id: 0
    period: 1000 # microseconds
    number_of_motors: 1
    type: unitree
    device: /dev/ttyUSB0

    motors:
      - index: 0
        id: 0
        gear_ratio: 6.33
        zero_offset: 0.0