add_library(kinematics
    src/kinematics.cpp
)
target_include_directories(kinematics
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/include
)
target_link_libraries(kinematics
    PUBLIC
        Eigen3::Eigen
        pinocchio::pinocchio
)

add_library(robot
    src/robot.cpp
)
target_include_directories(robot
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/include
)
target_link_libraries(robot
    PUBLIC
        motor
        sensor
        joy
        kinematics
        controller
        yaml-cpp
)

add_library(ARTI-H1
    src/robots/ARTI_H1.cpp
)
target_include_directories(ARTI-H1
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/include
)
target_link_libraries(ARTI-H1
    PUBLIC
        robot
)