masters:
  - id: 0
    period: 1000 # microseconds
    type: dynamixel
    device: /dev/Dynamixel

    motors:
      - id: 1
        gear_ratio: 1.0
        zero_offset: 0.0
        pulse_per_revolution: 4096
        min: -0.6
        max:  0.6