masters:
  - id: 0
    period: 1000 # microseconds
    type: unitree
    device: /dev/Unitree

    motors:
      - id: 1
        gear_ratio: 6.33
        zero_offset: 0.0
        pulse_per_revolution: 32768

      - id: 2
        gear_ratio: 6.33
        zero_offset: 0.0
        pulse_per_revolution: 32768
